var MSG = {
  catInOut:"IN/OUT",
  catDigital:"Digital",
  catAnalog:"Analog",
  catSerial:"Serial",
  catSoftSerial:"Software Serial",
  catServo:"Motor/Servo",
  catSensors:"Sensors",
  catDisplay:'Display',
  catSerialLCD:"Serial LCD",
  catSerialLCD_I2C:"Serial LCD I2C",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"String Vars", 
  catTime:"Time",
  catLogic: "Logic",
  catConversion:"Conversion",
  catAdvanced:"Advanced",
  catAdvancedMisc: "Misc",
  catEEPROM:"EEPROM",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catTone: "Tone",
  catLists: "Lists",
  catColour: "Colour",
  catVariables: "Variables",
  catFunctions: "Functions",
  catIot: "IOT",
  catIotGeneral: "General",
  catIotStation: "IOT Station",
  catIotServer: "IOT Server",
  catIotClient: "IOT Client",
  catIotAccessPoint: "IOT Access Point",
  catScan: "Scan",
  catWebService: "Web Services",
  catThingSpeak: "ThingSpeak",
  catWebPage: "Web Server",
  catInterrupts: "Interrupts",
  catJsonParser: "JSON Parser",
  title: "Code",
  blocks: "Blocks",
  linkTooltip: "Save and link to blocks.",
  runTooltip: "Download the code to open in Arduino IDE",
  saveXMLTooltip:"Save XML project",
  loadXMLTooltip:"Open XML project",
  copycodeTooltip:"Copy Arduino code into clipboard",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  discard: "Delete all %1 blocks?",
  trashTooltip: "Discard all blocks",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
